[package]
name = "rust-tests"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
rand = "0.3"
hex = "0.4.3"
ironfish_rust = { path = "../ironfish-rust" }
